import { Geist, Geist_Mono, Lilita_One } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getCurrentUser } from '@/app/lib/auth';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lilita = Lilita_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lilita-one",
});

export default async function RootLayout({ children }) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-end gap-8 p-8">
          <Link href='/tutor-panel' className="border-2 w-25 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-green-300 hover:border-green-400">Tutor Panel</Link>
          {user ?
            <>
              {user.type === 'admin' &&
                <Link href='/admin-panel' className="border-2 w-25 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-amber-300 hover:border-amber-400">
                  Admin Panel
                </Link>
              }
              <form action="/api/auth/signout" method="POST">
                <button className="border-2 w-20 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-red-300 hover:border-red-400">
                  Sign out
                </button>
              </form>
              <Link href='/my-profile' className="border-2 w-25 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-blue-300 hover:border-blue-400">
                My profile
              </Link>
            </> :
            <>
              <Link href='/signin' className="border-2 w-20 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-blue-300 hover:border-blue-400">
                Sign In
              </Link>
              <Link href='/signup' className="border-2 w-20 h-10 rounded-lg flex justify-center items-center cursor-pointer transition-colors duration-200 hover:bg-blue-300 hover:border-blue-400">
                Sign Up
              </Link>
            </>
          }
        </header>
        <main className="flex justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
